Traceback (most recent call last):
  File "tools/infer2.py", line 352, in <module>
    main(args)
  File "tools/infer2.py", line 306, in main
    coco_dt = coco_gt.loadRes("predictions_coco_format.json")
  File "/leonardo/home/userexternal/adivicin/rtdetr/lib/python3.8/site-packages/pycocotools/coco.py", line 329, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range
